server:
  port: 8080
  servlet:
    context-path: /lucky-draw/api/v1
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/lucky_draw}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${SIGNER_KEY:7/Yxq7uqBCDmMpVJgh93TAt9M7FyP2hpRC3kndtzUiLp/5bk/pUziyLzrFA3EEQ2f}
  valid-duration: 259200 #in second
  refreshable-duration:  777600 # in second
api:
  version: v1
  server:
    url: http://localhost:8080/lucky-draw/api/v1